@CleanTeeth.Api_HostAddress = http://localhost:5201/DentalOffices

Get {{CleanTeeth.Api_HostAddress}}/019B2222-BE59-7834-AA95-2ED175CD4217
Accept: application/json

##

Post {{CleanTeeth.Api_HostAddress}}
Content-Type: application/json

{
  "name": "Dental Office A"
}
###
